// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFXiWNnA_nptTfHT9CQxPkui2m9NGXe4',
    appId: '1:935281113392:web:04b5c191c09fe583dab0f5',
    messagingSenderId: '935281113392',
    projectId: 'chat-app-3d824',
    authDomain: 'chat-app-3d824.firebaseapp.com',
    storageBucket: 'chat-app-3d824.firebasestorage.app',
    measurementId: 'G-P64J1GHQJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnGnwNVModiLPaVOdxu3qBz7Kwu6GdFpw',
    appId: '1:935281113392:android:7e9938f998f63c8edab0f5',
    messagingSenderId: '935281113392',
    projectId: 'chat-app-3d824',
    storageBucket: 'chat-app-3d824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1UCiVMVOCA6yEMuOV77S59Io0HeDOtfk',
    appId: '1:935281113392:ios:935b8b36dea33ce4dab0f5',
    messagingSenderId: '935281113392',
    projectId: 'chat-app-3d824',
    storageBucket: 'chat-app-3d824.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1UCiVMVOCA6yEMuOV77S59Io0HeDOtfk',
    appId: '1:935281113392:ios:935b8b36dea33ce4dab0f5',
    messagingSenderId: '935281113392',
    projectId: 'chat-app-3d824',
    storageBucket: 'chat-app-3d824.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFFXiWNnA_nptTfHT9CQxPkui2m9NGXe4',
    appId: '1:935281113392:web:d32fac96776176d3dab0f5',
    messagingSenderId: '935281113392',
    projectId: 'chat-app-3d824',
    authDomain: 'chat-app-3d824.firebaseapp.com',
    storageBucket: 'chat-app-3d824.firebasestorage.app',
    measurementId: 'G-R487NG2YXJ',
  );
}
